#开启pprof
debug: false
#监听端口
httpPort: 80
httpsPort: 0
rpcPort: 10086
#机器信息
name: wsk-live
ip: 10.0.117.171
#mysql配置
databases:
  driver: mysql
  list:
    - name: eo_oslive
      username: root
      password: 123456
      port: 3306
      host: 127.0.0.1
      type: master
      maxIdleConnections: 40
      maxOpenConnections: 100
    - name: eo_oslive
      username: root
      password: 123456
      port: 3306
      host: 127.0.0.1
      type: slave
      maxIdleConnections: 40
      maxOpenConnections: 100
#日志
logger:
  path: /Users/yangsen/logs/
  format: -%Y%m%d
  infoFile: gowebcast-info
  errorFile: gowebcast-error
#redis配置
redis:
  cluster:
    - web-redis-cache-01.uat14.dom:52001
    - web-redis-cache-01.uat14.dom:52002
    - web-redis-cache-01.uat14.dom:52003
    - web-redis-cache-01.uat14.dom:52004
    - web-redis-cache-01.uat14.dom:52005
    - web-redis-cache-01.uat14.dom:52006
    - web-redis-cache-01.uat14.dom:52007
  password: ee@redis^#**
  minIdle: 50
  poolSize: 1000
#kafka配置
kafka:
  webcast:
    brokers: 10.0.13.181:9092,10.0.13.182:9092,10.0.13.183:9092
    zb:
      topic: webcast
      group: cast-1-dev
#证书
certFile: /Users/yangsen/zhengshu/server.crt
keyFile: /Users/yangsen/zhengshu/server.key
