#开启pprof
debug: false
#监听端口
httpPort: 8806
httpsPort: 0
rpcPort: 10010
#机器信息
name: cloud
#mysql配置
databases:
  driver: mysql
  list:
    - name: eo_osfile
      username: eeosfile
      password: T13_fajuwTf
      port: 62111
      host: web-mysql-os-writer-01.db.sit13.dom
      type: master
      maxIdleConnections: 40
      maxOpenConnections: 100
    - name: eo_osfile
      username: eeosfile
      password: T13_fajuwTf
      port: 62111
      host: web-mysql-os-writer-01.db.sit13.dom
      type: slave
      maxIdleConnections: 40
      maxOpenConnections: 100
#日志
logger:
  path: ./logs/
  format: -%Y%m%d
  infoFile: cloud-info
  errorFile: cloud-error
#redis配置
redis:
  cluster:
    - web-redis-cache-01.uat14.dom:52001
    - web-redis-cache-01.uat14.dom:52002
    - web-redis-cache-01.uat14.dom:52003
    - web-redis-cache-01.uat14.dom:52004
    - web-redis-cache-01.uat14.dom:52005
    - web-redis-cache-01.uat14.dom:52006
    - web-redis-cache-01.uat14.dom:52007
  password: ee@redis^#**
  minIdle: 50
  poolSize: 1000
#kafka配置
kafka:
  webcast:
    brokers: 10.0.13.181:9092,10.0.13.182:9092,10.0.13.183:9092
    zb:
      topic: webcast
      group: cast-1-dev
#consul相关配置
consul:
  host: 'consul.sit13.dom:61170'
  tag: jup
  token: p2BE1AtpwPbrxZdC6k+eXA==